-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1.2 (64-bit)
-- Version: 2022.1.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tiled_conv_tiled_conv_Pipeline_VITIS_LOOP_154_3_VITIS_LOOP_156_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    empty : IN STD_LOGIC_VECTOR (4 downto 0);
    layer1_output_V_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    layer1_output_V_0_ce0 : OUT STD_LOGIC;
    layer1_output_V_0_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    linear_input_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    linear_input_V_ce0 : OUT STD_LOGIC;
    linear_input_V_we0 : OUT STD_LOGIC;
    linear_input_V_d0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of tiled_conv_tiled_conv_Pipeline_VITIS_LOOP_154_3_VITIS_LOOP_156_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln154_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal empty_30_fu_150_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_30_reg_346 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln156_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln156_reg_355 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln154_fu_183_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln154_reg_360 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln154_1_fu_201_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln154_1_reg_365 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln157_fu_209_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln157_reg_370 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_mid138_fu_237_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_mid138_reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln157_fu_315_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln157_reg_385 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln157_3_fu_310_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln157_fu_321_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tj_fu_50 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln156_fu_251_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_tj_load : STD_LOGIC_VECTOR (3 downto 0);
    signal tp_fu_54 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln154_3_fu_243_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_tp_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten40_fu_58 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln154_1_fu_162_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten40_load : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln154_fu_116_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln155_fu_120_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_29_fu_126_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl4_fu_138_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl3_fu_130_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl11_cast_fu_146_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln154_fu_171_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln154_1_fu_191_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln155_1_fu_195_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_32_fu_213_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl11_mid1_fu_225_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl10_mid1_fu_217_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl11_cast_mid1_fu_233_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_279_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_6_fu_272_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln157_1_fu_286_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln157_fu_290_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln157_2_fu_301_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln157_1_fu_304_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln154_2_fu_296_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component tiled_conv_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component tiled_conv_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten40_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln154_fu_156_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten40_fu_58 <= add_ln154_1_fu_162_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten40_fu_58 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    tj_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln154_fu_156_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    tj_fu_50 <= add_ln156_fu_251_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    tj_fu_50 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    tp_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln154_fu_156_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    tp_fu_54 <= select_ln154_3_fu_243_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    tp_fu_54 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln157_reg_385 <= add_ln157_fu_315_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                    empty_30_reg_346(7 downto 2) <= empty_30_fu_150_p2(7 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln154_fu_156_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln156_reg_355 <= icmp_ln156_fu_177_p2;
                    p_mid138_reg_375(7 downto 2) <= p_mid138_fu_237_p2(7 downto 2);
                select_ln154_1_reg_365 <= select_ln154_1_fu_201_p3;
                select_ln154_reg_360 <= select_ln154_fu_183_p3;
                trunc_ln157_reg_370 <= trunc_ln157_fu_209_p1;
            end if;
        end if;
    end process;
    empty_30_reg_346(1 downto 0) <= "00";
    p_mid138_reg_375(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln154_1_fu_162_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten40_load) + unsigned(ap_const_lv6_1));
    add_ln154_fu_171_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_tp_1) + unsigned(ap_const_lv2_1));
    add_ln155_1_fu_195_p2 <= std_logic_vector(unsigned(zext_ln154_1_fu_191_p1) + unsigned(empty));
    add_ln155_fu_120_p2 <= std_logic_vector(unsigned(zext_ln154_fu_116_p1) + unsigned(empty));
    add_ln156_fu_251_p2 <= std_logic_vector(unsigned(select_ln154_fu_183_p3) + unsigned(ap_const_lv4_1));
    add_ln157_1_fu_304_p2 <= std_logic_vector(unsigned(sub_ln157_fu_290_p2) + unsigned(zext_ln157_2_fu_301_p1));
    add_ln157_fu_315_p2 <= std_logic_vector(unsigned(zext_ln157_2_fu_301_p1) + unsigned(select_ln154_2_fu_296_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln154_fu_156_p2)
    begin
        if (((icmp_ln154_fu_156_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten40_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten40_fu_58)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten40_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten40_load <= indvar_flatten40_fu_58;
        end if; 
    end process;


    ap_sig_allocacmp_tj_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, tj_fu_50, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_tj_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_tj_load <= tj_fu_50;
        end if; 
    end process;


    ap_sig_allocacmp_tp_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, tp_fu_54)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_tp_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_tp_1 <= tp_fu_54;
        end if; 
    end process;

    empty_29_fu_126_p1 <= add_ln155_fu_120_p2(4 - 1 downto 0);
    empty_30_fu_150_p2 <= std_logic_vector(unsigned(p_shl3_fu_130_p3) - unsigned(p_shl11_cast_fu_146_p1));
    empty_32_fu_213_p1 <= add_ln155_1_fu_195_p2(4 - 1 downto 0);
    icmp_ln154_fu_156_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten40_load = ap_const_lv6_24) else "0";
    icmp_ln156_fu_177_p2 <= "1" when (ap_sig_allocacmp_tj_load = ap_const_lv4_C) else "0";
    layer1_output_V_0_address0 <= zext_ln157_3_fu_310_p1(8 - 1 downto 0);

    layer1_output_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer1_output_V_0_ce0 <= ap_const_logic_1;
        else 
            layer1_output_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    linear_input_V_address0 <= zext_ln157_fu_321_p1(8 - 1 downto 0);

    linear_input_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linear_input_V_ce0 <= ap_const_logic_1;
        else 
            linear_input_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    linear_input_V_d0 <= layer1_output_V_0_q0;

    linear_input_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            linear_input_V_we0 <= ap_const_logic_1;
        else 
            linear_input_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_mid138_fu_237_p2 <= std_logic_vector(unsigned(p_shl10_mid1_fu_217_p3) - unsigned(p_shl11_cast_mid1_fu_233_p1));
    p_shl10_mid1_fu_217_p3 <= (empty_32_fu_213_p1 & ap_const_lv4_0);
        p_shl11_cast_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl4_fu_138_p3),8));

        p_shl11_cast_mid1_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl11_mid1_fu_225_p3),8));

    p_shl11_mid1_fu_225_p3 <= (add_ln155_1_fu_195_p2 & ap_const_lv2_0);
    p_shl3_fu_130_p3 <= (empty_29_fu_126_p1 & ap_const_lv4_0);
    p_shl4_fu_138_p3 <= (add_ln155_fu_120_p2 & ap_const_lv2_0);
    select_ln154_1_fu_201_p3 <= 
        add_ln155_1_fu_195_p2 when (icmp_ln156_fu_177_p2(0) = '1') else 
        add_ln155_fu_120_p2;
    select_ln154_2_fu_296_p3 <= 
        p_mid138_reg_375 when (icmp_ln156_reg_355(0) = '1') else 
        empty_30_reg_346;
    select_ln154_3_fu_243_p3 <= 
        add_ln154_fu_171_p2 when (icmp_ln156_fu_177_p2(0) = '1') else 
        ap_sig_allocacmp_tp_1;
    select_ln154_fu_183_p3 <= 
        ap_const_lv4_0 when (icmp_ln156_fu_177_p2(0) = '1') else 
        ap_sig_allocacmp_tj_load;
    sub_ln157_fu_290_p2 <= std_logic_vector(unsigned(tmp_6_fu_272_p3) - unsigned(zext_ln157_1_fu_286_p1));
    tmp_6_fu_272_p3 <= (trunc_ln157_reg_370 & ap_const_lv4_0);
    tmp_7_fu_279_p3 <= (select_ln154_1_reg_365 & ap_const_lv2_0);
    trunc_ln157_fu_209_p1 <= select_ln154_1_fu_201_p3(4 - 1 downto 0);
    zext_ln154_1_fu_191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln154_fu_171_p2),5));
    zext_ln154_fu_116_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_tp_1),5));
    zext_ln157_1_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_279_p3),8));
    zext_ln157_2_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln154_reg_360),8));
    zext_ln157_3_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln157_1_fu_304_p2),64));
    zext_ln157_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln157_reg_385),64));
end behav;
